### PR TITLE
dev -> PROD

### PR DESCRIPTION
**Pull request by OlliesWorld**
update Bruno and Barbano links
Added github api for profile images

### CODE REVIEW

**Comment by OlliesWorld** [comment]
updated workflow with API_GITHUB_TOKEN
and cleaned up index page

**Review by ch264 — CHANGES_REQUESTED** [review]
App breaks when pulling down

**Comment by ch264** [comment]
Screenshot 2023-04-20 at 10 05 58 AM

**Comment by OlliesWorld** [comment]
close for now

**Pull request closed without merging**
